<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
            'name' => 'Nike Air Force 1',
                'slug' => 'nike-air-force-1',
                'description' => 'Giày thể thao Nike Air Force 1 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-1.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Air Max 90',
                'slug' => 'nike-air-max-90',
                'description' => 'Giày thể thao Nike Air Max 90 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-2.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Air Jordan 1',
                'slug' => 'nike-air-jordan-1',
                'description' => 'Giày thể thao Nike Air Jordan 1 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-3.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Dunk Low',
                'slug' => 'nike-dunk-low',
                'description' => 'Giày thể thao Nike Dunk Low chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-4.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Blazer Mid 77',
                'slug' => 'nike-blazer-mid-77',
                'description' => 'Giày thể thao Nike Blazer Mid 77 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-5.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Air Max 97',
                'slug' => 'nike-air-max-97',
                'description' => 'Giày thể thao Nike Air Max 97 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-6.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike React Infinity Run',
                'slug' => 'nike-react-infinity-run',
                'description' => 'Giày thể thao Nike React Infinity Run chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-7.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Pegasus 40',
                'slug' => 'nike-pegasus-40',
                'description' => 'Giày thể thao Nike Pegasus 40 chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-8.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike ZoomX Vaporfly Next',
                'slug' => 'nike-zoomx-vaporfly-next',
                'description' => 'Giày thể thao Nike Nike ZoomX Vaporfly Next chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-9.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike SB Dunk High',
                'slug' => 'nike-sb-dunk',
                'description' => 'Giày thể thao Nike SB Dunk High chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-10.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Air Max',
                'slug' => 'nike-air-max',
                'description' => 'Giày thể thao Nike Air Max chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-11.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Nike Air Max Plus (TN Air)',
                'slug' => 'nike-air-max-plus',
                'description' => 'Giày thể thao Nike Air Max Plus (TN Air) chất lượng cao.',
                'price' => 2500000,
                'image' => 'images/products/nike-12.png',
                'category_id' => rand(1, 8),
                'brand_id' => 4,
            ],
            [
                'name' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'description' => 'Giày chạy bộ Adidas Ultraboost 22 với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-1.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas NMD R1',
                'slug' => 'adidas-nmd-r1',
                'description' => 'Giày chạy bộ Adidas NMD R1 với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-2.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Superstar',
                'slug' => 'adidas-superstar',
                'description' => 'Giày chạy bộ Adidas Superstar với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-3.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Stan Smith',
                'slug' => 'adidas-stan-smith',
                'description' => 'Giày chạy bộ Adidas Stan Smith với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-4.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Yeezy Boost 350 V2',
                'slug' => 'adidas-yeezy-boost-350-v2',
                'description' => 'Giày chạy bộ Adidas Yeezy Boost 350 V2 với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-5.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Forum Low',
                'slug' => 'adidas-forum-low',
                'description' => 'Giày chạy bộ Adidas Forum Low với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-6.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Gazelle',
                'slug' => 'adidas-gazelle',
                'description' => 'Giày chạy bộ Adidas Gazelle với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-7.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Samba OG',
                'slug' => 'adidas-samba-og',
                'description' => 'Giày chạy bộ Adidas Samba OGt với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-8.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas ZX 750',
                'slug' => 'adidas-zx-750',
                'description' => 'Giày chạy bộ Adidas ZX 750 với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-9.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Predator Freak',
                'slug' => 'adidas-predator-freak',
                'description' => 'Giày chạy bộ Adidas Predator Freak với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-10.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Adidas Harden Vol. 7',
                'slug' => 'adidas-harden-vol-7',
                'description' => 'Giày chạy bộ Adidas Harden Vol. 7 với công nghệ Boost.',
                'price' => 3000000,
                'image' => 'images/products/adidas-11.png',
                'category_id' => rand(1, 8),
                'brand_id' => 1,
            ],
            [
                'name' => 'Puma Suede Classic',
                'slug' => 'puma-suede-classic',
                'description' => 'Giày sneaker Puma Suede Classic phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-1.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma RS-X',
                'slug' => 'puma-rs-x',
                'description' => 'Giày sneaker Puma RS-X phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-2.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Future Rider',
                'slug' => 'puma-future-rider',
                'description' => 'Giày sneaker Puma Future Rider phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-3.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Cali',
                'slug' => 'puma-cali',
                'description' => 'Giày sneaker Puma Cali phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-4.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Clyde OG',
                'slug' => 'puma-clyde-og',
                'description' => 'Giày sneaker Puma Clyde OG phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-5.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Ignite',
                'slug' => 'puma-ignite',
                'description' => 'Giày sneaker Puma Ignite phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-6.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Deviate Nitro',
                'slug' => 'puma-deviate-nitro',
                'description' => 'Giày sneaker Puma Deviate Nitro phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-7.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Smash V2',
                'slug' => 'puma-smash-v2',
                'description' => 'Giày sneaker Puma Smash V2 phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-8.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Slipstream',
                'slug' => 'puma-slipstream',
                'description' => 'Giày sneaker Puma Slipstream phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-9.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Axelion',
                'slug' => 'puma-axelion',
                'description' => 'Giày sneaker Puma Axelion phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-10.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Puma Ultra Ultimate',
                'slug' => 'puma-ultra-ultimate',
                'description' => 'Giày sneaker Puma Ultra Ultimate phong cách hiện đại.',
                'price' => 2200000,
                'image' => 'images/products/puma-11.png',
                'category_id' => rand(1, 8),
                'brand_id' => 5,
            ],
            [
                'name' => 'Asics Gel-Kayano 30',
                'slug' => 'asics-gel-kayano-30',
                'description' => 'Giày chạy bộ Asics Gel-Kayano 30 với hỗ trợ cao cấp.',
                'price' => 2700000,
                'image' => 'images/products/asics-1.png',
                'category_id' => rand(1, 8),
                'brand_id' => 2,
            ],
            [
                'name' => 'Asics Gel-Nimbus 26',
                'slug' => 'asics-gel-nimbus-26',
                'description' => 'Giày chạy bộ Asics Gel-Nimbus 26 với hỗ trợ cao cấp.',
                'price' => 2700000,
                'image' => 'images/products/asics-2.png',
                'category_id' => rand(1, 8),
                'brand_id' => 2,
            ],
            [
                'name' => 'Asics Novablast 4',
                'slug' => 'asics-novablast-4',
                'description' => 'Giày chạy bộ Asics Asics Novablast 4 với hỗ trợ cao cấp.',
                'price' => 2700000,
                'image' => 'images/products/asics-3.png',
                'category_id' => rand(1, 8),
                'brand_id' => 2,
            ],
            [
                'name' => 'Asics Metaspeed Sky+',
                'slug' => 'asics-metaspeed-sky-plus',
                'description' => 'Giày chạy bộ Asics Metaspeed Sky+ với hỗ trợ cao cấp.',
                'price' => 2700000,
                'image' => 'images/products/asics-4.png',
                'category_id' => rand(1, 8),
                'brand_id' => 2,
            ],
            [
                'name' => 'Asics GT-2000 12',
                'slug' => 'asics-gt-2000-12',
                'description' => 'Giày chạy bộ Asics GT-2000 12 với hỗ trợ cao cấp.',
                'price' => 2700000,
                'image' => 'images/products/asics-5.png',
                'category_id' => rand(1, 8),
                'brand_id' => 2,
            ],
            [
                'name' => 'Bata North Star Kick',
                'slug' => 'bata-north-star-kick',
                'description' => 'Giày da Bata North Star Kick phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-1.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Power Xtreme',
                'slug' => 'bata-power-xtreme',
                'description' => 'Giày da Bata Power Xtreme phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-2.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Red Label Casual',
                'slug' => 'bata-red-label-casual',
                'description' => 'Giày da Bata Red Label Casual phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-3.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Weinbrenner Trek',
                'slug' => 'bata-weinbrenner-trek',
                'description' => 'Giày da Bata Weinbrenner Trek phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-4.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Comfit Walker',
                'slug' => 'bata-comfit-walker',
                'description' => 'Giày da Bata Comfit Walker phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-5.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Bubblegummers Kids Sneakers',
                'slug' => 'bata-bubblegummers-kids-sneakers',
                'description' => 'Giày da Bata Bubblegummers Kids Sneakers phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-6.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Tennis Classic',
                'slug' => 'bata-tennis-classic',
                'description' => 'Giày da Bata Tennis Classic phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-7.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Ambassador Formal',
                'slug' => 'bata-ambassador-formal',
                'description' => 'Giày da Bata Ambassador Formal phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-8.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata School Shoes (B.First)',
                'slug' => 'bata-school-shoes-b-first',
                'description' => 'Giày da Bata School Shoes (B.First) phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-9.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
            [
                'name' => 'Bata Heritage Hotshot',
                'slug' => 'bata-heritage-hotshot',
                'description' => 'Giày da Bata Heritage Hotshot phong cách lịch lãm.',
                'price' => 1500000,
                'image' => 'images/products/bata-10.png',
                'category_id' => rand(1, 8),
                'brand_id' => 3,
            ],
        ];


        foreach ($products as $product) {
            Product::create([
                'name' => $product['name'],
                'slug' => Str::slug($product['name']),
                'description' => $product['description'],
                'price' => $product['price'],
                'image' => $product['image'],
                'category_id' => $product['category_id'],
                'brand_id' => $product['brand_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
